# Generated by Django 5.1.4 on 2026-06-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('usuarios', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_procesados', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('qr', 'Código QR'), ('efectivo', 'Efectivo')], max_length=20),
        ),
    ]
