# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_pago_usuario_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='caja_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='caja_cerrada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
