# Generated by Django 5.1.4 on 2026-07-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_opinion'),
        ('pedidos', '0006_detallepreorden_observaciones'),
        ('producto', '0002_combo_combodetalle'),
        ('usuarios', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_por_bs', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_puntos',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo')], max_length=15)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('limite_usos', models.PositiveIntegerField(default=1)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cupon',
            },
        ),
        migrations.CreateModel(
            name='CuponUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confirmado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='finanzas.cupon')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_usados', to='finanzas.pago')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_usados', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_usados', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'cupon_uso',
            },
        ),
        migrations.CreateModel(
            name='PuntoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganado', 'Ganado'), ('usado', 'Usado'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolucion')], max_length=20)),
                ('puntos', models.IntegerField()),
                ('saldo_resultante', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to='pedidos.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_puntos', to='producto.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'punto_movimiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
