# Generated by Django 5.1.4 on 2026-06-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallepedido_observaciones_pedido_notas_and_more'),
        ('usuarios', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='usuario_confirmacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
