# Generated by Django 5.1.4 on 2026-06-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_cliente_notificacion_tipo'),
        ('pedidos', '0004_pedido_descuento_pedido_promocion'),
    ]

    operations = [
    ]
