# Generated by Django 5.1.4 on 2026-07-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_configuracionpuntos_cupon_cuponuso_puntomovimiento'),
        ('pedidos', '0006_detallepreorden_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='finanzas.cupon'),
        ),
    ]
