# Generated by Django 6.0.4 on 2026-04-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
