# Generated by Django 5.1.4 on 2026-04-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_bitacora_y_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
