# Generated by Django 6.0.4 on 2026-04-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_codigo_recuperacion_alter_usuario_contrasena_and_more'),
        ('usuarios', '0003_bitacora_y_roles'),
    ]

    operations = [
    ]
