# Generated by Django 5.1.4 on 2026-05-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_bitacora_id'),
        ('usuarios', '0005_alter_cliente_options_alter_empleado_options_and_more'),
    ]

    operations = [
    ]
