# Generated by Django 6.0.4 on 2026-05-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_cliente_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-timestamp']},
        ),
    ]
