# Generated by Django 5.1.4 on 2026-05-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_bitacora_options'),
        ('usuarios', '0006_merge_20260501_2034'),
    ]

    operations = [
    ]
