# Generated by Django 6.0.4 on 2026-05-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_mesa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salatematica',
            name='imagen',
        ),
        migrations.AddField(
            model_name='salatematica',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible'), ('mantenimiento', 'En mantenimiento'), ('reservada', 'Reservada')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='salatematica',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='salas/'),
        ),
        migrations.AddField(
            model_name='salatematica',
            name='tematica',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.CreateModel(
            name='SalaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='salas/galeria/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='reservas.salatematica')),
            ],
            options={
                'db_table': 'sala_imagen',
            },
        ),
    ]
