# Generated by Django 5.1.4 on 2026-05-12 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_salatematica_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación'), ('recordatorio', 'Recordatorio'), ('cancelacion', 'Cancelación'), ('modificacion', 'Modificación')], max_length=20)),
                ('mensaje', models.TextField()),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reservas.reserva')),
            ],
            options={
                'db_table': 'notificacion_reserva',
            },
        ),
    ]
