# Generated by Django 5.1.4 on 2026-05-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_preorden_estados_nuevos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallepreorden',
            name='preorden',
        ),
        migrations.RemoveField(
            model_name='detallepreorden',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='preorden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='preorden',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='preorden',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='preorden',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='preorden',
            name='usuario_mesero',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='DetallePreorden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Preorden',
        ),
    ]
