# Generated by Django 5.1.4 on 2026-06-01 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_producto_categoria_and_more'),
        ('usuarios', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionreserva',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='notificacionreserva',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallo', 'Fallo')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacionreserva',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificacionreserva',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
